export const POKEMON_LIST_REQUEST = 'POKEMON_LIST_REQUEST'
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS'
export const POKEMON_LIST_FAIL = 'POKEMON_LIST_FAIL'

export const LIKED_POKEMON_LIST_REQUEST = 'LIKED_POKEMON_LIST_REQUEST'
export const LIKED_POKEMON_LIST_SUCCESS = 'LIKED_POKEMON_LIST_SUCCESS'
export const LIKED_POKEMON_LIST_FAIL = 'LIKED_POKEMON_LIST_FAIL'