export const POKEMON_LIST_REQUEST = 'POKEMON_LIST_REQUEST'
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS'
export const POKEMON_LIST_FAIL = 'POKEMON_LIST_FAIL'

export const LIKED_POKEMON_LIST_REQUEST = 'LIKED_POKEMON_LIST_REQUEST'
export const LIKED_POKEMON_LIST_SUCCESS = 'LIKED_POKEMON_LIST_SUCCESS'
export const LIKED_POKEMON_LIST_FAIL = 'LIKED_POKEMON_LIST_FAIL'

export const LIKE_POKEMON_REQUEST = 'LIKE_POKEMON_REQUEST'
export const LIKE_POKEMON_SUCCESS = 'LIKE_POKEMON_SUCCESS'
export const LIKE_POKEMON_FAIL = 'LIKE_POKEMON_FAIL'

export const SEARCH_POKEMON_REQUEST = 'SEARCH_POKEMON_REQUEST'
export const SEARCH_POKEMON_SUCCESS = 'SEARCH_POKEMON_SUCCESS'
export const SEARCH_POKEMON_FAIL = 'SEARCH_POKEMON_FAIL'

export const SEARCH_LIKED_POKEMON_REQUEST = 'SEARCH_LIKED_POKEMON_REQUEST'
export const SEARCH_LIKED_POKEMON_SUCCESS = 'SEARCH_LIKED_POKEMON_SUCCESS'
export const SEARCH_LIKED_POKEMON_FAIL = 'SEARCH_LIKED_POKEMON_FAIL'